apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base

labels:
  - pairs:
      environment: local
      platform.example.com/managed-by: argocd
      platform.example.com/application: hello-service

    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  platform.example.com/environment: local
  platform.example.com/owner: platform-team