apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: demo
labels:
- pairs:
    platform.example.com/environment: local
    platform.example.com/application: order-service
    platform.example.com/managed-by: idp-platform
  includeSelectors: false
commonAnnotations:
  platform.example.com/environment: local
  platform.example.com/owner: order-team
